openapi: 3.1.0
info:
  title: Entropic API
  version: "0.1.0"
servers:
  - url: https://entropic-api.onrender.com
paths:
  /predictlife:
    post:
      summary: Get a symbolic impression
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PredictionRequest'
      responses:
        '200':
          description: Symbolic impression
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PredictionResponse'
components:
  schemas:
    PredictionRequest:
      type: object
      properties:
        question:
          type: string
        include_details:
          type: boolean
      required:
        - question
    Symbol:
      type: object
      properties:
        label:
          type: string
        category:
          type: string
        tone:
          type: string
        meaning:
          type: string
    Details:
      type: object
      properties:
        bitstring:
          type: string
        entropy:
          type: number
        num_qubits:
          type: integer
    PredictionResponse:
      type: object
      properties:
        symbol:
          $ref: '#/components/schemas/Symbol'
        details:
          $ref: '#/components/schemas/Details'